### ISSUE TITLE
Invalid arguments ' Candidates are: void sleep(?) '

### ISSUE THREAD

**Issue by sledgeh** [gnuarmeclipse/plug-ins#101]
I all examples in `main.cpp` file in all lines where `timer.sleep` present Eclipse warns with message: Semantic error *Invalid arguments ' Candidates are: void sleep(?) '* and shows pictogram "bug". Toolchain can compile it. 
How can I shut up Eclipse?

**Comment by sledgeh** [comment]
I fixed it while composing message.
Disable Preferences -> C/C++ -> Code Analysis -> Syntax and Semantec Errors -> Invalid arguments or all group. 
May be this is real semantec error and should be fixed? Or Eclipse is not enough clever?

**Comment by ilg-ul** [comment]
did you try project properties -> Index -> Rebuild ?

**Comment by sledgeh** [comment]
Many times.

**Comment by ilg-ul** [comment]
from my experience on OS X, these errors appear only in the initial project, after reindexing and closing/opening the files, they are no longer shown.

**Comment by sledgeh** [comment]
Yes, they appear only in the initial project. And reindexing fixes the problem. On Linux too.

**Comment by daveloyall** [comment]
And windows.  Rebuilding the index does fix it.

**Comment by caot** [comment]
`project properties -> Index -> Rebuild` also fixed the follows:
`Problem description: Invalid arguments ' Candidates 
 are: void __builtin_va_end(char * (*)()) '`

**Comment by positron96** [comment]
Sorry for digging this up, but where is Index -> Rebuild in the current version of Eclipse?

![image](https://user-images.githubusercontent.com/2095278/70131509-00691600-16b5-11ea-9ac0-3eb2c4869c13.png)
