### ISSUE TITLE
Allow project Settings page to open when Toolchain is undefined 

### ISSUE THREAD

**Issue by iulia-vasii** [gnuarmeclipse/plug-ins#106]
Plug-in version: ilg.gnuarmeclipse.repository-2.11.1-201512141335, GNU ARM C/C++ Cross Compiler 2.1.1.201512141335
Eclipse version: Eclipse Mars (4.5.1)
Java version: 1.7

Steps to reproduce:
In case a toolchain is added and after removed (valid use case, see #41), the Settings page becomes invalid and cannot be opened anymore. The GNU ARM plug-in should select a default toolchain instead and allow user to fix the project configuration.

**Comment by ilg-ul** [comment]
should be ok now. 

no need to post issues if you post pull requests.

**Comment by ilg-ul** [comment]
fixed in 2.12.1-201604190915
