### ISSUE TITLE
J-Link Enable Flash Breakpoints checkbox doesn't change launch config

### ISSUE THREAD

**Issue by sukidog** [gnuarmeclipse/plug-ins#108]
Fix on its way.

Steps to reproduce:
1. Create a J-Link launch configuraiton
2. Ensure the configuration is not dirty (the Apply button is disabled)
3. Switch to Startup tab and toggle 'Enable flash breakpoints'.
BUG: notice Revert and Apply buttons do not become enabled. You can close the launch config and reopen it and you'll see the setting did not change.

**Comment by ilg-ul** [comment]
thank you, I'll investigate.

no need to post issues if you post pull requests.

**Comment by sukidog** [comment]
Well, the fix is quite simple and in a pull request, so reviewing the fix may be a more efficient path than investigating the problem.

**Comment by ilg-ul** [comment]
I'm quite busy now with other parts of the project, but I'll return to the plug-ins and apply your pull request.

**Comment by ilg-ul** [comment]
fixed in v3.2.1-201701141320
