### ISSUE TITLE
How to re-enable files excluded from build?

### ISSUE THREAD

**Issue by pamisisi** [gnuarmeclipse/plug-ins#11]
hello, ilg-ul.

Why the default state `system/src/stm32f1-stdperiph/` some xxx.c is Not enabled? How to enable them?
I `system/src/stm32f1-stdperiph/*.c` copy to `system/include/stm32f1-stdperiph/` directory. This problem can be solved!

![screenshot from 2015-10-15 02-20-29](https://cloud.githubusercontent.com/assets/5887346/10502275/f30a0662-731c-11e5-9c0c-279fcbf5fbe4.png)

![screenshot from 2015-10-15 02-24-21](https://cloud.githubusercontent.com/assets/5887346/10502298/29235f96-731d-11e5-8a5f-97c822e3fa11.png)

* plug-in version : 2.9.3
* Eclipse version : Eclipse IDE for C/C++ Developers Version: Mars.1 Release (4.5.1) Build id: 20150924-1200
* Java version: 1.8.0_51
* operating system: Gentoo/Linux 64-bit
* toolchain version: gcc-arm-none-eabi-4_9-2015q3

**Comment by ilg-ul** [comment]
> Why the default state system/src/...  xxx.c is Not enabled?

because you asked so when you created the project, by enabling _Exclude unused_.

> How to enable them?

right click → **Resource Configurations** → **Exclude from build** → uncheck

> copy source files  to `system/include/stm32f1-stdperiph/` directory

wrong solution, should not put source files in include folders.
