### ISSUE TITLE
Unable to get the packs plug-in

### ISSUE THREAD

**Issue by hellgheast** [gnuarmeclipse/plug-ins#110]
Hello,
When i download from eclipse the packs plug-in (with the list of devices),it didn't work.
I download it succesfully but when i restart Eclipse it seems that he didn't found any file in .cache (who is not existing) .

I already tried to rename the package folder but it didn't change anything

**Comment by ilg-ul** [comment]
sorry, with the provided information I cannot diagnose your problem.

and for support use the project forum, not the issues tracker.
