### ISSUE TITLE
Question: debugging support for Freescale FRDM-K64F

### ISSUE THREAD

**Issue by Hillsie** [gnuarmeclipse/plug-ins#121]
Hi There, 
I'm using a Freescale Mbed prototyping board and having a problem with the onboard debugger with my current toolset. I just wanted to check if your project has support for debugging this device.
Thanks

**Comment by ilg-ul** [comment]
this project has direct support for any device supported by SEGGER J-Link, OpenOCD or pyOCD.

if you want to use the on board programmer and can load j-link firmware, this is the recommended way to go.

**Comment by ilg-ul** [comment]
for future questions please use the project forum.
