### ISSUE TITLE
Don't generate makefile if the project not change

### ISSUE THREAD

**Issue by dumarjo** [gnuarmeclipse/plug-ins#132]
Hi,

I would like to know if its' possible to not regenerate all the makefile everytime ? When a project have a 10 folder it's not that bad, but in our case we build a project with more than 500 file in 100 folder. Only to generate makefiles, this take 30 to 45 second. 

Probably trigger the generation of the makefile only on file added/removed/excluded from build/change project setting should be the way to go. 

Regards

Jonathan

**Comment by ilg-ul** [comment]
makefile generation is done by CDT.
