### ISSUE TITLE
parameter checking problem of debug.gdbjtag.jlink

### ISSUE THREAD

**Issue by noodlefighter** [gnuarmeclipse/plug-ins#134]
### Description

While debug, i want to startup the JLink GBD Server manually, but a little problem happened.
### Steps to Reproduce
1. "Debug Configurations" - "GDB SEGGER J-Link Debugging" - 
2. found the checkbox "Debugger" - "J-Link GDB Server Setup" -  "Start the J-Link GDB server locally" and uncheck it.
3. make sure there is _no text in the textbox "Device Name"_.
4. Launch Debugging

**Expected behavior:** [What you expected to happen]
Error hint:

```
Missing mandatory device name. Fill-in the 'Device name:' field in the Debugger tab.
```
### Versions
- debug.gdbjtag.jlink 4.1.1.201606210758
- eclipse version: neon release (4.6.0)
- jre version: jre-8u102-windows-x64
- Windows 7 Ultimate
- GNU Tools ARM Embedded 4.9 2015q2

**Comment by ilg-ul** [comment]
thank you, I'll investigate and fix it.

**Comment by ilg-ul** [comment]
please try the beta 3.2.1-201608181714 from updates-test and let me know if the problem was solved.
