### ISSUE TITLE
Internal builder generates .bin file only after project clean

### ISSUE THREAD

**Issue by vortex314** [gnuarmeclipse/plug-ins#135]
### Description

When doing a first time build or a build after "project clean", the console shows that the last step of converting .elf to .bin is executed. If however I do an incremental build , the console shows that the .elf is generated but the last step of converting .elf to .bin is not done.

### Context
- Windows 7
- Eclipse Mars
- latest version of GNU ARM Eclipse
- Internal builder configured

**Comment by ilg-ul** [comment]
> Internal builder configured

the CDT internal builder is no longer supported and should not be used.

**Comment by vortex314** [comment]
Thanks for the swift response, I'll try with external builder, requiring installation of make.

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/windows-build-tools/

**Comment by vortex314** [comment]
You guys, thought about everything !  Amazing work. Please continue.
