### ISSUE TITLE
License of C/C++ code ?

### ISSUE THREAD

**Issue by bogdanm** [gnuarmeclipse/plug-ins#139]
I can't find the license of the C/C++ code in this repository (for example the files under https://github.com/gnuarmeclipse/plug-ins/tree/develop/ilg.gnuarmeclipse.templates.stm/templates/stm32f4xx_exe_c_project). I want to re-distribute these files in another project (independent of Eclipse) and I don't know if I can do that, or what license to list for them if I can.

**Comment by ilg-ul** [comment]
C/C++ code normally should refer to the µOS++, which is release under the MIT License.
 
so, from my point of view, you can redistribute the files in any other projects (well, maybe except North Korean nuclear bombs or similar).

legally all you have to do is to mention the µOS++ project (http://micro-os-plus.github.io) and the MIT license.

**Comment by bogdanm** [comment]
Thanks! That's all I needed to know.

**Comment by ilg-ul** [comment]
btw, the code used by the current templates is getting obsolete.

for a glimpse of the future templates, you can check the demo projects from:

https://github.com/micro-os-plus/eclipse-demo-projects
