### ISSUE TITLE
objcopy fails for C++ code when .text and .data checked in eclipse settings - solved

### ISSUE THREAD

**Issue by vortex314** [gnuarmeclipse/plug-ins#142]
### Description
The issue has been solved , I am leaving this message here with the appropriate title so it can help others.
I spend some weeks on diagnosing why I was not able to have a bootloader (STM32 ) to execute some .bin file while I was able to execute the corresponding .elf file via Segger loader.
The pitfall is that objcopy with the option -j 'section-name' only includes the named section into the .bin file, no others. So while checking the boxes on .data and .text, you tell in fact to ignore other sections.

If you create however C++ code therer is a chance that you have a static initializer / constructor of a C++ class. These constructors get called in a section .init_array before start of the 'main' function.

So when the .init_array section is not copied to the image, probably a random pointer or 0 gets called, which stops further execution.
If you don't flag any of the .text and .data sections, then all necessary code gets copied into the .bin file.

Hope this helps somebody...

**Comment by ilg-ul** [comment]
thank you.
