### ISSUE TITLE
Keil packs server down, returns 404 for .pdsc files

### ISSUE THREAD

**Issue by Gogin79** [gnuarmeclipse/plug-ins#15]
Hi, I have a problem with update pack. You can not execute refresh package. In the error window is writen : "http://www.keil.com/pack/.......pdsc." Failed to open connection, response code 404. I re-install Eclipse and OFF antivirus. I do not know where I find fault. Please help. Thank you beforhand for your time.

**Comment by ilg-ul** [comment]
the keil.com server returns 404 for all .pdsc files

please report the problem to Keil.

**Comment by Gogin79** [comment]
9 items added and other items with error. I have 96 clicks items. I did not have more on my nerves :-).

Ok, I write to keil.

**Comment by ilg-ul** [comment]
Some of the packages are stored on vendor server, those are available. Most of them are on keil.com, and these fail.

**Comment by Gogin79** [comment]
I understand. I wrote to KEIL. I will wait and see what will happen. 

I will write as soon as I get a message from KEIL.

**Comment by Virtex6** [comment]
It is working again. Downloaded all the *.pdsc files.

**Comment by ilg-ul** [comment]
I confirm.
