### ISSUE TITLE
"OpenOCD plug-in" link incorrect

### ISSUE THREAD

**Issue by johnmoule** [gnuarmeclipse/plug-ins#154]
The hypertext link near the bottom of the "How to install the OpenOCD binaries" page incorrectly links to:

http://gnuarmeclipse.github.io/debug/qemu/#define-the-openocd-folder-location.

It should link to  

http://gnuarmeclipse.github.io/debug/openocd/#define-the-openocd-folder-location

**Comment by ilg-ul** [comment]
thank you for the report, I'll fix the link, but please note that the documentation site is a separate GitHub, with its own issues page.
