### ISSUE TITLE
Pack sort issue

### ISSUE THREAD

**Issue by pearson** [gnuarmeclipse/plug-ins#157]
This is a minor issue, but it's one that caught me off guard. The versions of the packs are sorted in normal alphanumeric order when (IMHO) they should be sorted by version number.  (Or, perhaps, by date.)

See the attached image for an example. The newer 8.11.1 version of this pack is far down the list of available packs, and wasn't visible in my default window layout. 

![packs sort order](https://cloud.githubusercontent.com/assets/656880/21440339/6b96671c-c847-11e6-9231-98fd65a99623.PNG)

**Comment by ilg-ul** [comment]
you are right, the order should be based on numerical versions.

**Comment by ilg-ul** [comment]
#198
