### ISSUE TITLE
MK22FN128VLH10  in GNU ARM Eclipse

### ISSUE THREAD

**Issue by carlosdelfino** [gnuarmeclipse/plug-ins#161]
Hi @ilg-ul .

I'm studying the use of Freescale's MK22FN128VLH10 in small project, I saw that the GNU ARM Eclipse only has the KL family, is there any special procedure I can follow to use a layout for the MK22 family?

Or should I start with the KL family and make the file adjustments for the MK22?

Grateful.

**Comment by ilg-ul** [comment]
for NXP devices probably the easiest way is to use KDS to create the project.

**Comment by carlosdelfino** [comment]
I'm going to start studying Kinetics today, I saw that it is possible to install the plugins for eclipse, I want to continue to keep everything in Eclipse.

Thank you.

**Comment by carlosdelfino** [comment]
Is the GNU ARM Eclipse referenced in NXP Kinets is yours?

**Comment by ilg-ul** [comment]
yes.
