### ISSUE TITLE
Eclipse Update Site Offline

### ISSUE THREAD

**Issue by MrBuddyCasino** [gnuarmeclipse/plug-ins#165]
This URL does not work:
http://gnuarmeclipse.sourceforge.net/updates

Eclipse says there is no update site there. Did I miss anything?

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/blog/2016/12/02/plugins-install-issue/

**Comment by MrBuddyCasino** [comment]
That worked - thanks for the quick reply!

**Comment by ilg-ul** [comment]
duplicate of #151
