### ISSUE TITLE
plugin site down?

### ISSUE THREAD

**Issue by tothero** [gnuarmeclipse/plug-ins#169]
No repository found at http://gnuarmeclipse.sourceforge.net/updates.

since yesterday when installing into a fresh neon.2 install...

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/blog/2016/12/02/plugins-install-issue/

**Comment by tothero** [comment]
okey, will try :-) thank you!

**Comment by tothero** [comment]
java update did work! :-)

**Comment by ilg-ul** [comment]
duplicate of #151, #158, #165

**Comment by ilg-ul** [comment]
> java update did work!

I'm convinced. clearly documented (for those who read documentations).
