### ISSUE TITLE
Issue with OpenOCD Debug configuration

### ISSUE THREAD

**Issue by cnoviello** [gnuarmeclipse/plug-ins#173]
Hi,
The latest release seems to have an issue with the OpenOCD debug configuration. If you create a new OpenOCD Debug Configuration and uncheck the "Start OpenOCD locally" checkbox (in Debugger settings), then when you try to launch the debug configuration the following error dialog appears:

![](http://www.carminenoviello.com/wp-content/uploads/2017/01/2017-01-29-12_33_37-Problem-Occurred.png)

**Comment by ilg-ul** [comment]
thank you, I'll investigate.

**Comment by ilg-ul** [comment]
fixed since 3.3.1-201702241122
