### ISSUE TITLE
Suggestion: Show command line in console

### ISSUE THREAD

**Issue by daveloyall** [gnuarmeclipse/plug-ins#174]
I think that when you invoke Debug, it should some how print the entire command line it will invoke to the console.

**Comment by ilg-ul** [comment]
right click on the process name in the tree gives you the full command line.

**Comment by daveloyall** [comment]
Doesn't work when qemu crashes immediately.

**Comment by ilg-ul** [comment]
fixed since 3.3.1-201702241049

however, printing the command line to console did not help much, since the console output is normally not visible.

the solution I used was to log the line in the Eclipse log file (.metadata/.log); it is not more visible either, but at least it is persistent.

**Comment by daveloyall** [comment]
@ilg-ul, thank you.  This will probably help somebody one day!

Cheers,
--Dave
