### ISSUE TITLE
J-Link Debug Plugin: Accept ':' as J-Link IP address

### ISSUE THREAD

**Issue by ErichStyger** [gnuarmeclipse/plug-ins#177]
### Description
J-Link has a cool feature (https://www.segger.com/jlink-remoteserver.html). For this, I need to use 'ip tunnel:<serialno>' to connect to the tunneling server. The GNU ARM Eclipse J-Link Debug Plugin (Debugger > Connection > IP) allows to enter an ip address (e.g. 192.168.0.55 or localhost), but does not allow to enter a colon ':'. So I cannot specify a tunnel address.

### Steps to Reproduce
1. Go the the J-Link Debugger Launch configuration, 'Debugger' Tab
2. Select 'IP' as connection
3. try to enter
tunnel:609100567
as IP address

**Expected behavior:** [What you expected to happen]
I can enter e.g. "tunnel:609100567" (colon accepted)
**Actual behavior:** [What actually happened]
Colon (:) is accepted.

**Workaround:
Interestingly, I can copy-paste tunnel:609100567 from the clip-board (at least on Windows), but I cannot type ':' in that edit box.

### Versions

* [plug-in version]
  GNU ARM C/C++ J-Link Debugging	4.1.2.201701141320	ilg.gnuarmeclipse.debug.gdbjtag.jlink.feature.group	Liviu Ionescu
* [Eclipse version]
Eclipse Mars
* [Java version]
1.8.0_121-b13
* [operating system]
Windows 10
* [toolchain version]
GNU ARM Embedded 4.8

Please understand that without being able to reproduce the bug we cannot identify your problem.

**Comment by ilg-ul** [comment]
added since 3.3.1-201702240856
