### ISSUE TITLE
Add Cortex-M33 to Hello World template device list

### ISSUE THREAD

**Issue by GWolters** [gnuarmeclipse/plug-ins#183]
### Description
Cannot select Cortex-m33 when I create a new C project

Description of the bug or feature:
Cortex-m33 is not shown in the drop-down list, in the menu, that appears when you create a new C project. 
### Steps to Reproduce
1. Press File => New C project
2. Fill in project name, select Hello World Arm Cortex-M  C/C++ project
3. Press Next, a new window pops up.Select drop down list # Processor core:
- only M0, M0+, M3, M4 and M7 show up, no M33. 
Cortex-M-33 should show up.

### Versions

* [plug-in version]     3.3.1-201702251311
* [Eclipse version]      Mars and Neon
* [Java version]          JDK 8.0.121
* [operating system] Win32
* [toolchain version]

**Comment by ilg-ul** [comment]
fixed, please check the beta version 3.4.1-201703241311 from updates-test.
