### ISSUE TITLE
org.eclipse.equinox.p2.core.ProvisionException & Eclipse Kepler

### ISSUE THREAD

**Issue by Joohanness** [gnuarmeclipse/plug-ins#184]
Hello, 

i was trying to add the GNU ARM Plug-In in Eclipse (http://gnuarmeclipse.sourceforge.net/updates) but i always get this log: 

> Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.
Unable to read repository at http://gnuarmeclipse.sourceforge.net/updates/content.xml.
peer not authenticated

I also attached a Picture, which Shows the error. 

I hope someone can help me to solve this Problem. 

Eclipse:
Version: Kepler Service Release 2
Build id: 20140224-0627

Java:
Version 8 Update 121
Build: 1.8.0_121-b13

![unbenannt](https://cloud.githubusercontent.com/assets/26169325/23559411/3f486106-0037-11e7-8713-e6981dbff754.jpg)

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/blog/2017/01/29/plugins-install-issue/

**Comment by Joohanness** [comment]
Thank you for your answer, your advice solved my Problem but an other log have occurred. 

> Cannot complete the install because one or more required items could not be found.
  Software being installed: GNU ARM C/C++ Cross Compiler 2.3.1.201702251311 (ilg.gnuarmeclipse.managedbuild.cross.feature.group 2.3.1.201702251311)
  Missing requirement: GNU ARM C/C++ Core 3.3.1.201702251311 (ilg.gnuarmeclipse.core 3.3.1.201702251311) requires 'bundle org.eclipse.cdt 8.6.0' but it could not be found
  Cannot satisfy dependency:
    From: GNU ARM C/C++ Cross Compiler 2.3.1.201702251311 (ilg.gnuarmeclipse.managedbuild.cross 2.3.1.201702251311)
    To: bundle ilg.gnuarmeclipse.core 0.0.0
  Cannot satisfy dependency:
    From: GNU ARM C/C++ Cross Compiler 2.3.1.201702251311 (ilg.gnuarmeclipse.managedbuild.cross.feature.group 2.3.1.201702251311)
    To: ilg.gnuarmeclipse.managedbuild.cross [2.3.1.201702251311]

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/plugins/install/#eclipse--cdt

**Comment by Joohanness** [comment]
Thank you your advices helped me to solve all my Problems. Thank you very much.

**Comment by ilg-ul** [comment]
you are welcome. I guess we can close this ticket now.

**Comment by nayefroqaya** [comment]
I had the same problem but with installing scala 

http://download.scala-ide.org/sdk/lithium/e46/scala212/stable/site
but the solution did not work.??? any suggestions ?

**Comment by ilg-ul** [comment]
yes, use the latest java JDK and install the separate strong encryption package from oracle.

**Comment by divyasujeeth** [comment]
Hi.. Need help. When I try to download package from Neon(URL : ) Im getting the below error. I have tried assigning proxy and also installed SSL Extender for further assistance with this. Unable to connect to repository.

![error neon](https://user-images.githubusercontent.com/39622468/40543287-5636f9fc-6041-11e8-89cd-1885350e014a.jpg)
![error neon](https://user-images.githubusercontent.com/39622468/40543290-598bd2a8-6041-11e8-993a-4202a29a712c.jpg)

**Comment by ilg-ul** [comment]
if you have limited net access, you won't get too far.
