### ISSUE TITLE
Usability problems with the debugging Tabs on OS X

### ISSUE THREAD

**Issue by ilg-ul** [gnuarmeclipse/plug-ins#26]
On small screens, the content of some debugger configuration windows is too long, and require scrolling the window, which, on OS X, sometimes is difficult.

Ideally the tabs should be redesigned to fit a normal laptop screen without having to use the scroll bars.

(Migrated from [SF support-requests#78](https://sourceforge.net/p/gnuarmeclipse/support-requests/78/)).

**Comment by dholth** [comment]
I haven't figured out how to get the bars to scroll at all on an OSX laptop.

**Comment by ilg-ul** [comment]
well, this is tricky, but it is possible. 

unfortunately this is an Eclipse problem, and there is nothing the plug-ins can do to fix it.

**Comment by ilg-ul** [comment]
solved as #144 since 3.4.1
