### ISSUE TITLE
What does "Not yet used during build" mean?

### ISSUE THREAD

**Issue by xiaoyaojiujian** [gnuarmeclipse/plug-ins#28]
"Not yet used during build!" how to handle it?
![pax50fr kd cjud8z k1](https://cloud.githubusercontent.com/assets/5345756/10731815/168ef782-7c32-11e5-8b67-12151204ec4f.png)

**Comment by xiaoyaojiujian** [comment]
I follow the tutorials to do,http://gnuarmeclipse.github.io/eclipse/project/assign-device/
But always show errors,"Not yet used during build"
how to assign device?

**Comment by ilg-ul** [comment]
> how to assign device?

simply select the desired device.

the "Not yet used during build" message informs you that the selection is not yet used during builds, only the debuggers consider it, to select the peripheral registers.

**Comment by xiaoyaojiujian** [comment]
Thank you for your answer.
More detailed introduction about these steps?
This tool is different from "Keil".You just need to select the device type, write code, and then directly debug.You don't need to worry about other things, only cares about the code.
 I'm sorry, I'm a newbie.

**Comment by ilg-ul** [comment]
all available documentation is at http://gnuarmeclipse.github.io/

good luck with your projects!

**Comment by ilg-ul** [comment]
For such questions, in the future please use the GNU ARM Eclipse forum, available at http://www.element14.com/community/groups/gnu-arm-eclipse.
