### ISSUE TITLE
problems running debug session

### ISSUE THREAD

**Issue by JLPOLSL** [gnuarmeclipse/plug-ins#29]
gnuarmeclipse openocd plugin stops with 
"Error in final launch sequence
Failed to execute MI command:
-exec-run"
This used to work correctly and now after standard installation of eclipse (4.4 or 4.5) and gnuarmeclipse plugins  it seems to start openocd debug session as a local one instead of remote.

**Comment by ilg-ul** [comment]
please see https://github.com/gnuarmeclipse/plug-ins/issues/3

**Comment by JLPOLSL** [comment]
It was my issue too - gdb got upgraded to 7.10 with updated toolchain - this is what I missed. Thanks for directing me to the right place :-)
