### ISSUE TITLE
Linker flags not shown for C++ projects

### ISSUE THREAD

**Issue by joelm-somnium** [gnuarmeclipse/plug-ins#40]
For C++ projects, the 'Linker flags' box is not shown at:
Project properties > C/C++ Build > Settings > Cross ARM C++ Linker > Miscellaneous

For C projects it is shown.

* v2.6.1-201502281154
* Eclipse 4.5.1
* Java 1.7.0_60
* Windows 8.1

**Comment by ilg-ul** [comment]
thank you, I'll investigate.

**Comment by ilg-ul** [comment]
I checked, and in both cases the **Other linker flags** is visible. See attached images. 

What other box do you mean?


![c](https://cloud.githubusercontent.com/assets/362732/11418782/c7a78e56-942b-11e5-9526-742841aebe08.png)
![cpp](https://cloud.githubusercontent.com/assets/362732/11418783/c7cbf322-942b-11e5-83a1-4279c7dd94aa.png)

**Comment by joelm-somnium** [comment]
The Linker flags box is visible in a C project above the Other objects box.

![c-linkerflags](https://cloud.githubusercontent.com/assets/16003100/11421313/e149e9a8-942b-11e5-99b8-e266cc9d10dc.png)

Attached is a patch that appears to correct the issue.

[issue40-linkerflags-patch.txt](https://github.com/gnuarmeclipse/plug-ins/files/44869/issue40-linkerflags-patch.txt)

**Comment by ilg-ul** [comment]
ah, now I see.

merged.

please check the GitHub repository and 2.11.1-201511261230 from updates test.

**Comment by ilg-ul** [comment]
fixed in 2.11.1-201512141335
