### ISSUE TITLE
Do not use Synaptics to install Eclipse on Linux, it does not work

### ISSUE THREAD

**Issue by clarkleach** [gnuarmeclipse/plug-ins#46]
I get the following when trying to install Cross Compiler and OpenOCD plugins:

Cannot complete the install because one or more required items could not be found.
  Software being installed: GNU ARM C/C++ Cross Compiler 1.15.2.201511061603 (ilg.gnuarmeclipse.managedbuild.cross.feature.group 1.15.2.201511061603)
  Missing requirement: GNU ARM C/C++ Core 2.10.2.201511061603 (ilg.gnuarmeclipse.core 2.10.2.201511061603) requires 'bundle org.eclipse.debug.core 3.8.0' but it could not be found
  Cannot satisfy dependency:
    From: GNU ARM C/C++ Cross Compiler 1.15.2.201511061603 (ilg.gnuarmeclipse.managedbuild.cross 1.15.2.201511061603)
    To: bundle ilg.gnuarmeclipse.core 0.0.0
  Cannot satisfy dependency:
    From: GNU ARM C/C++ Cross Compiler 1.15.2.201511061603 (ilg.gnuarmeclipse.managedbuild.cross.feature.group 1.15.2.201511061603)
    To: ilg.gnuarmeclipse.managedbuild.cross [1.15.2.201511061603]

**Comment by ilg-ul** [comment]
it looks like you do not have CDT. are you sure you installed **Eclipse IDE for C/C++ Developers** and not a different Eclipse?

**Comment by clarkleach** [comment]
I thought I did.  I installed it via Synaptics package manager which apprently presents its own set of issues.  I'm in the process of re-installing it manually...

**Comment by clarkleach** [comment]
That went much better.  Installed plugins without a hitch.  Now for the real test; see if I can get openocd to work with my FT2232D interface.

**Comment by ilg-ul** [comment]
> I installed it via Synaptics package manager

hmmmm... where does the documentation say to use the Synaptics package manager?

when I suggest to follow the documentation 'by the book', I expect people to do exactly so. it is clearly stated that not doing so is a big source of trouble.

**Comment by clarkleach** [comment]
Where in the documentation does it say anything about installing Eclipse?

**Comment by ilg-ul** [comment]
http://gnuarmeclipse.github.io/plugins/install/#eclipse--cdt

**Comment by ilg-ul** [comment]
For such question, in the future please use the GNU ARM Eclipse forum, available at http://www.element14.com/community/groups/gnu-arm-eclipse.
