### ISSUE TITLE
Tool Settings Tab not available for Makefile projects

### ISSUE THREAD

**Issue by abencomo** [gnuarmeclipse/plug-ins#5]
I've followed all the installation steps and I'm able to run both tutorials (Blinky ARM test & Hello ARM test) without problems.  However, when I import a project into Eclipse via Import > "Existing Code as Makefile Project", then the Properties - Setting dialog is missing the "Tool Settings" tab and others tabs (see attachments). To reproduce, just reimport the Hello ARM test project.

Eclipse IDE for C/C++ Version: Mars Release (4.5.0) Build id: 20150621-1200
gnuarmeclipse-qemu-osx-2.3.50-201508041609-dev
gcc-arm-none-eabi-4_9-2015q3
OSX 10.10.4

<img width="771" alt="screen shot 2015-09-26 at 12 21 06 pm" src="https://cloud.githubusercontent.com/assets/7515273/10119368/1cbc9cd2-6449-11e5-951e-e442f5bab5d6.png">

<img width="468" alt="screen shot 2015-09-26 at 12 35 24 pm" src="https://cloud.githubusercontent.com/assets/7515273/10119464/772930ac-644b-11e5-9084-69012046c1cc.png">

<img width="969" alt="screen shot 2015-09-26 at 12 36 04 pm" src="https://cloud.githubusercontent.com/assets/7515273/10119467/7fc04fde-644b-11e5-9667-a877a7fb335f.png">

**Comment by ilg-ul** [comment]
>  Import > "Existing Code as Makefile Project" ... then the Properties - Setting dialog is missing the "Tool Settings" tab

what Tool Settings you would like to set for a **Makefile project**?

the only setting available for unmanaged projects is the toolchain, used by the indexer, and this settings, as seen before, is available.

the rest of the settings are available only for managed C/C++ projects.

**Comment by abencomo** [comment]
I'm not sure why you labeled your reply as a question when it seems that you're actually proving a answer to it already (i.e. "the only setting available for unmanaged projects is the toolchain"). 

Anyhow, I guess it is just confusing that the same hello project can have different settings based on how it was added into the workspace.  So, if you create the hello project via File > New > C Project, then it is managed.  However, if you reimport this originally managed project back to the workspace via Import > Existing Code as Makefile Project, then it becomes unmanaged.  Is that what you meant with your Question/Answer?

**Comment by abencomo** [comment]
I figured out how to bring the Tool Settings Tab back.  This was not obvious to me so I'm documenting it here in case someone else has the same question.  In the project properties > C/C++ Build > tab "Builder Settings", just check the box for the option "Generate Makefiles automatically" and that will bring back the Tool Settings Tab as shown below.

BEFORE:
<img width="839" alt="screen shot 2015-09-26 at 10 23 46 pm" src="https://cloud.githubusercontent.com/assets/7515273/10121393/105b25f8-649e-11e5-80dc-eaba80a3f4e5.png">
<img width="839" alt="screen shot 2015-09-26 at 10 23 59 pm" src="https://cloud.githubusercontent.com/assets/7515273/10121392/105b2026-649e-11e5-8980-85c0eb4a0959.png">

AFTER:
<img width="838" alt="screen shot 2015-09-26 at 10 24 32 pm" src="https://cloud.githubusercontent.com/assets/7515273/10121394/105da79c-649e-11e5-98a4-d8d68abf77a4.png">
<img width="839" alt="screen shot 2015-09-26 at 10 24 44 pm" src="https://cloud.githubusercontent.com/assets/7515273/10121395/105dd1ae-649e-11e5-9d88-e92f4c17e785.png">

**Comment by ilg-ul** [comment]
Your conclusion about managed and unmanaged projects is mostly correct, just that generally not all unmanaged projects can be converted to managed with a single click. Most complex makefiles have hand-written rules that cannot be automatically generated by Eclipse.

The mistake in your approach was to use **Import** -> **Existing Code as Makefile Project** instead of **Import** -> **General** -> **Existing Projects into Workspace**. Always use _Existing Projects_ for projects created by Eclipse, regardless of their type  (i.e. if you have a `.project` file, possibly a `.cproject` file for C/C++ projects, Eclipse will know its type and how to import it). Use _Existing Code as Makefile Project_ only for projects that were created manually, and have a Makefile but do not have a `.project` file.
