### ISSUE TITLE
Showing OpenOCD and PEMicro under MacOSx when trying to "Install New Software"

### ISSUE THREAD

**Issue by mzan** [gnuarmeclipse/plug-ins#67]
Hello,
we have an enhancement request for your OpenOCD and PEMicro features. The problem is, they are not supported on MacOSx, but we have them on our KDS updates site for Linux and Win, so when you try the "Install New Software" they show up and can be installed. Could you please add OS dependency on Linux and Win under the "Supported Environments" in those feature? It would prevent users from accidentally installing them. I guess this is reproducible on any Eclipse/Java/Mac/plug-ins versions. Thank you. 

Best regards,
Michal Zan

**Comment by ilg-ul** [comment]
you must be missing something, GNU ARM Eclipse does not provide support for PEMicro, and OpenOCD was always available for OS X.

**Comment by mzan** [comment]
yeah, you are right, sorry, my fault
