### ISSUE TITLE
CMSIS-PACK: wish to disable pack repositories

### ISSUE THREAD

**Issue by ErichStyger** [gnuarmeclipse/plug-ins#71]
Because it takes a lot of time to refresh/fetch the data from the repositories, currently I delete from the repository list and add them later on.

I wish there would be a checkbox (similar to the Eclipse update sites) so I can disable repositories I would like not to get contacted for performance reasons.

![package repositories](https://cloud.githubusercontent.com/assets/3187954/13029046/1ae91646-d281-11e5-9a7b-aa43c8c024b3.jpg)

**Comment by ilg-ul** [comment]
somehow fixed since 3.4.1, I added a new Type: Unused.

it is not as elegant as with a new button, but it was much easier to implement.
