### ISSUE TITLE
Export GNU ARM Eclipse project

### ISSUE THREAD

**Issue by robertfoss** [gnuarmeclipse/plug-ins#81]
Hi,

I currently have a working GNU ARM Eclipse project and I would like to be able to export it so that it is independent of GNU ARM Eclipse, but still builds using a simple make call.

Is there a way of doing this?
How does eclipse internally invoke make?
 

Rob.

**Comment by ilg-ul** [comment]
Please use this tracker only for bug reports, for questions the project forum should be more appropriate.
