### ISSUE TITLE
[cross plugin] Cannot add the Toolchain path after applying new settings.

### ISSUE THREAD

**Issue by iulia-vasii** [gnuarmeclipse/plug-ins#90]
Plug-in version: ilg.gnuarmeclipse.repository-2.11.1-201512141335, GNU ARM C/C++ Cross Compiler 2.1.1.201512141335
Eclipse version: Eclipse Mars (4.5.1)
Java version: 1.7
OS: Win 7 64

Steps to reproduce:
- create ARM project
- select other toolchain name in Settings -> Toolchains tab
- Apply
- try to set the Toolchain path by selecting "global"/"workspace"/"project" link

Note that the newly selected toolchain does not appear on "Tools Path" page, only the old one.
User must press OK button and re-do the whole process to be able to add the toolchain path.

**Comment by ilg-ul** [comment]
fixed in 2.12.1-201604190915
