### ISSUE TITLE
CMSIS Pack Manager: would be nice to import packages from local repository

### ISSUE THREAD

**Issue by marek-trmac** [gnuarmeclipse/plug-ins#95]
e.g. support URL in with "file:" scheme.
User can easily create repository on his local machine and import selected packages.

**Comment by ilg-ul** [comment]
did you try it? the code to process the url is generic, I thought it works with any url.

you need to provide an index file, similar to the one from keil.com.

**Comment by marek-trmac** [comment]
The problem is in ilg.gnuarmeclipse.packs.data.Repos.getFileNamePrefixFromUrl(String)
1) ':' character is not converted
2) file:/// prefix is not removed
3) '\' character is not supported, cannot be used in URL

**Comment by in4lio** [comment]
Hello, I confirm local repo does't work.

**Comment by ilg-ul** [comment]
> 3) '\' character is not supported, cannot be used in URL

that's normal, to avoid problems, in Eclipse you should always use POSIX paths, even on Windows.

**Comment by in4lio** [comment]
But, for now, it's possible to add the package into the.cache and manually update .repos.xml)

**Comment by marek-trmac** [comment]
Fixed by pull request #95

**Comment by ilg-ul** [comment]
if you confirm the version from updates-test is ok, we can close this ticket.

**Comment by marek-trmac** [comment]
updates-test works well.
For a reference, here is example how URL should look like:
`file:///c:/nxp/CMSIS_Pack_Repo/index.idx`
